common: &common
  database: closure_tree_test<%= ENV['TRAVIS_JOB_NUMBER'].to_s.gsub(/\W/, '_') %>
  host: localhost
  pool: 50
  timeout: 5000
  reaping_frequency: 1000
  min_messages: ERROR

sqlite:
  adapter: <%= "jdbc" if defined? JRUBY_VERSION %>sqlite3
  database: 'closure_tree_test'

postgresql:
  <<: *common
  adapter: postgresql
  username: postgres

mysql:
  <<: *common
  adapter: mysql2
  username: root
